# meta.yaml
package:
  name: metafun
  version: "1.0.0"

source:
  path: .

build:
  number: 0
  noarch: generic

requirements:
  run:
    - python >=3.10
    - apptainer =1.3.0
    - nextflow =24.04.2
    - dash =2.17.1
    - dash-bootstrap-components
    - dash-core-components
    - dash-html-components
    - dash-table
    - dash-daq
    - plotly >=5.0
    - pandas >=2.0
    - tqdm
    - sylph =0.6.1
    - numpy >=1.26
    - squashfuse

test:
  commands:
    - which metafun
    - metafun -h

about:
  home: https://github.com/aababc1/metaFun
  license: MIT
  summary: Custom package for metaFun workflow management
  description: |
    A comprehensive package that includes custom scripts and workflows
    for metaFun analysis pipeline. Version 1.0.0 adds WMS_STRAIN module
    for strain-level microbial diversity analysis using inStrain.
