# meta.yaml
package:
  name: metafun
  version: "0.1.1"

source:
  path: .

build:
  number: 0
  preserve_empty_dirs: true  
  #script: bash build.sh

requirements:
  host:
    - python=3.12

    - pip
  run:
    - python=3.12
    - apptainer=1.3.0
    - nextflow=24.04.2
    - dash=2.17.1
    - dash-bootstrap-components=1.7.1
    - dash-core-components=2.0.0
    - dash-html-components=2.0.0
    - dash-table=5.0.0
    - dash-daq=0.5.0
    - plotly=5.22.0
    - pandas=2.2.2
    - tqdm=4.66.4
    - sylph=0.6.1
    - numpy=2.0.0
app:
  entry: metafun

test:
  commands:
    - which metafun
    - metafun -h


about:
  home: https://github.com/aababc1/metaFun
  license: MIT
  summary: Custom package for metaFun workflow management
  description: |
    A comprehensive package that includes custom scripts and workflows
    for metaFun analysis pipeline.
