library(ComplexHeatmap)
library(circlize)
library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)
library(RColorBrewer)

args <- commandArgs(trailingOnly = TRUE)

if (length(args) == 0) {
    cat("No arguments provided. Exiting script.\n -i : Input is CARD csv result generated by add_rgi_togenePA.py, -m metadata CSV file, -out output heatmap file, -meta_cols : metadata column numbers like 2,3,4\n")
  quit(save = "no", status = 1)
}
arg_list <- list()
for (i in seq(1, length(args), 2)) {
  arg_list[[args[i]]] <- args[i + 1]
}


input_csv <- arg_list[["-i"]]
metadata_file <- arg_list[["-m"]]
output_file <- arg_list[["-out"]]
meta_col_selected <- arg_list[["-mc"]]
meta_col_selected <- as.integer(meta_col_selected)
meta_cols <- NULL
output_html <- arg_list[["-out_html"]]

if ("-meta_cols" %in% names(arg_list)) {
    meta_cols <- unlist(strsplit(arg_list[["-meta_cols"]], ","))
}


vfdb_raw <- read.csv(input_csv, header = TRUE, check.names = FALSE)
metadata <- read.csv(metadata_file, header = TRUE, check.names = FALSE)
selected_colname = colnames(metadata)[meta_col_selected]
print(selected_colname)
if (ncol(vfdb_raw) - 7 != nrow(metadata)) {
    stop("Mismatch in the number of columns in heatmap data and the number of rows in metadata.")
}



# for visualization partitioning
# group_col_name <- colnames(metadata_file)[as.integer(meta_col_selected)]
heatmap_data <- vfdb_raw[, 2:(ncol(vfdb_raw) - 6)]


vf_info <- vfdb_raw[, (ncol(vfdb_raw) - 5):ncol(vfdb_raw)] # last 6 fields

heatmap_data_summarized <- heatmap_data %>% 
  mutate(VFID = vf_info$VF_ID) %>%
  group_by(VFID) %>%
  summarise_all(sum)
character_data <- vf_info %>%
  group_by(VF_ID) %>%
  summarise_all(~first(.))

heatmap_data_summarized <- bind_cols(character_data, heatmap_data_summarized)
heatmap_data_summarized$VF_ID <- factor(heatmap_data_summarized$VF_ID)
heatmap_data_summarized$VFC_ID <- factor(heatmap_data_summarized$VFC_ID)

set.seed(33)
vf_names <- unique(heatmap_data_summarized$VF_ID)
vfc_categories <- unique(heatmap_data_summarized$VFC_ID)
vf_colors <- rainbow(length(vf_names))
vfc_colors <- rainbow(length(vfc_categories))
vf_color_map <- setNames(vf_colors, vf_names)
vfc_color_map <- setNames(vfc_colors, vfc_categories)
head(vf_color_map)
head(vfc_color_map)
# heatmap_data_summarized$VF_ID <- factor(heatmap_data_summarized$VF_ID, levels = vf_names)
# heatmap_data_summarized$VFC_ID <- factor(heatmap_data_summarized$VFC_ID, levels = vfc_categories)
heatmap_data_summarized$VF_ID <- factor(heatmap_data_summarized$VF_ID, levels = names(vf_color_map))
heatmap_data_summarized$VFC_ID <- factor(heatmap_data_summarized$VFC_ID, levels = names(vfc_color_map))

all(names(vf_color_map) %in% levels(heatmap_data_summarized$VF_ID)) # Should return TRUE
all(names(vfc_color_map) %in% levels(heatmap_data_summarized$VFC_ID)) # Should return TRUE


head(heatmap_data_summarized)
# metadata add 
rownames(metadata) <- metadata[,1]

selected_columns <- c("Completeness", "Contamination", "classification", colnames(metadata[selected_colname])) #meta1380 %>% select(ncol(.)))
meta_filtered_forvis <- metadata[, selected_columns]
head(meta_filtered_forvis)
# meta_filtered_forvis$colnames(meta_filtered_forvis[selected_colname]) <- replace(meta_filtered_forvis$colnames(metadata[selected_colname]),
#                                           meta_filtered_forvis$colnames(metadata[selected_colname])=='',"NA")
meta_filtered_forvis <- meta_filtered_forvis %>%
  mutate(!!selected_colname := replace(.[[selected_colname]], .[[selected_colname]] == "", "NA"))

print(meta_filtered_forvis)

classification_split <- strsplit(as.character(meta_filtered_forvis$classification), ";")
classification_df <- do.call(rbind, classification_split)
colnames(classification_df) <- c("Domain", "Phylum", "Class", "Order", "Family", "Genus", "Species")
classification_df <- as.data.frame(classification_df)

meta_filtered_forvis <- cbind(meta_filtered_forvis[, -which(colnames(meta_filtered_forvis) == "classification")], classification_df)
head(meta_filtered_forvis)

meta_filtered_forvis_ordered <- meta_filtered_forvis[match(colnames(heatmap_data), rownames(meta_filtered_forvis)),]



# heatmap visualiztion add annotation
top_annotation <- HeatmapAnnotation(df = meta_filtered_forvis_ordered,
                                    annotation_name_gp = gpar(fontsize = 7)) 
# row_annotation <- HeatmapAnnotation(
#   VF_Name = anno_text(heatmap_data_summarized$VF_ID),
#   VFcategory = anno_text(heatmap_data_summarized$VFC_ID),
#   which='row',annotation_name_gp = gpar(fontsize = 7))
print(levels(heatmap_data_summarized$VF_ID))
print(levels(heatmap_data_summarized$VFC_ID))
head(heatmap_data_summarized)

row_annotation <-HeatmapAnnotation(
   VF_Name = heatmap_data_summarized$VF_ID,
   VFcategory = heatmap_data_summarized$VFC_ID,
   which='row',annotation_name_gp = gpar(fontsize = 7)
)

print(row_annotation)
print("error?")
print(summary(heatmap_data_summarized[,8:ncol(heatmap_data_summarized)]))

vfdb_matrix<- heatmap_data_summarized[,8:ncol(heatmap_data_summarized)]

breaks <- c(0, min(vfdb_matrix[vfdb_matrix>0]), max(vfdb_matrix))
colors <- c("lightgrey", "white", "red")
vfdb_matrix <- as.matrix(heatmap_data_summarized[,8:ncol(heatmap_data_summarized)])
if (length(unique(as.vector(vfdb_matrix))) == 1) {

  my_color_function <- "red"
} else {
  my_color_function <- colorRamp2(breaks,colors)
}


heatmap <- Heatmap(
  as.matrix(heatmap_data_summarized[,8:ncol(heatmap_data_summarized)]),
  name = "Virulence Factors",
  col = my_color_function,
  top_annotation = top_annotation,
  right_annotation = row_annotation,
  show_row_names = FALSE,
  show_column_names = FALSE,
  show_column_dend = FALSE,
  column_split  = meta_filtered_forvis_ordered[,selected_colname]
)
# Save heatmap to file
output_file <- "heatmap_VFDB.pdf"

pdf(file = output_file, width = 20, height = 15)
draw(heatmap)
dev.off()



library(ragg)
library(ComplexHeatmap)
library(circlize)
library(InteractiveComplexHeatmap)

heatmap <- draw(heatmap)
htShiny(heatmap, output_ui_float = TRUE, save = output_html)